anchors_path: /cluster/daidalos/sgiebenhain/anchors_39.npy
data:
  n_expressions: 1
  n_subjects: 300
  root: /cluster/angmar/sgiebenhain/synth_data_2neutral
decoder:
  decoder_hidden_dim: 200
  decoder_lat_dim_glob: 64
  decoder_lat_dim_loc: 32
  decoder_nlayers: 4
  decoder_nloc: 39
  decoder_nsymm_pairs: 16
  dropout: false
  type: deep_sdf_decoder
  weight_norm: false
encoder: null
lm_inds_path: /cluster/daidalos/sgiebenhain/lm_inds_39.npy
training:
  batch_size: 32
  ckpt_interval: 500
  grad_clip: 0.1
  grad_clip_lat: 0.1
  lambdas:
    anchors: 7.5
    grad: 0.1
    lat_reg: 0.01
    middle_dist: 0.0
    normals: 0.3
    space_sdf: 0.01
    surf_sdf: 2.0
    symm_dist: 0.01
  loss_type: igr
  lr: 0.0005
  lr_decay_factor: 0.5
  lr_decay_factor_lat: 0.5
  lr_decay_interval: 5000
  lr_decay_interval_lat: 5000
  lr_lat: 0.001
  mode: shape_space
  npoints_decoder: 750
  npoints_decoder_non: 250
  sigma_near: 0.01
  weight_decay: 0.01
