opt:
    alpha: 5000
    lambda_rgb: 100.
    lambda_eikonal: 0.0
    lambda_mask: 10.0
    lambda_geo3d: 0
    lambda_rgb3d: 0
    lambdas_reg:
        symm_dist_geo: 1.0
        symm_dist_app: 1.0
        reg_unobserved_geo: 0.0
        reg_loc_geo: 75 #333
        reg_loc_app: 333
        reg_global_geo: 15 #50
        reg_global_app: 50
    lambda_reg_expr: 100
    n_epochs: 251
    rays_per_batch: 450
ray_tracer:
    object_bounding_sphere: 0.7
    n_steps: 32
reconstruction:
    min: [ -0.55, -0.5, -0.95 ]
    max: [ 0.55, 0.75, 0.4 ]
    res: 150  # small for faster reconstruction # use 256 or higher to grasp reconstructed geometry better
